import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Firebase options for the current app.
///
/// This follows the structure generated by the FlutterFire CLI.
/// Re-run `flutterfire configure` later if you register additional desktop apps
/// or change bundle/package identifiers.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66tRS4CcgFyhBoGDcKt8EQmQpzzp-Wgk',
    appId: '1:430029536167:web:234678dbb6420a27c6d482',
    messagingSenderId: '430029536167',
    projectId: 'pai-project-ai',
    authDomain: 'pai-project-ai.firebaseapp.com',
    storageBucket: 'pai-project-ai.firebasestorage.app',
    measurementId: 'G-NS2VHZVQVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDBrYi6YtMoUeVuKVcWXGAr6z_NF_Q84',
    appId: '1:430029536167:android:793f7a1ed1fe4134c6d482',
    messagingSenderId: '430029536167',
    projectId: 'pai-project-ai',
    storageBucket: 'pai-project-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTslzRUzpw3T_kRa8E-hGxRw0op2n51Bw',
    appId: '1:430029536167:ios:8d6059895561893fc6d482',
    messagingSenderId: '430029536167',
    projectId: 'pai-project-ai',
    storageBucket: 'pai-project-ai.firebasestorage.app',
    iosBundleId: 'com.example.pai',
  );

  // This uses the same Apple Firebase app until a dedicated macOS app is
  // registered with FlutterFire.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTslzRUzpw3T_kRa8E-hGxRw0op2n51Bw',
    appId: '1:430029536167:ios:8d6059895561893fc6d482',
    messagingSenderId: '430029536167',
    projectId: 'pai-project-ai',
    storageBucket: 'pai-project-ai.firebasestorage.app',
    iosBundleId: 'com.example.pai',
  );

  // Desktop options can be replaced with dedicated desktop app configs once
  // those apps are registered in Firebase.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC66tRS4CcgFyhBoGDcKt8EQmQpzzp-Wgk',
    appId: '1:430029536167:web:234678dbb6420a27c6d482',
    messagingSenderId: '430029536167',
    projectId: 'pai-project-ai',
    authDomain: 'pai-project-ai.firebaseapp.com',
    storageBucket: 'pai-project-ai.firebasestorage.app',
    measurementId: 'G-NS2VHZVQVE',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC66tRS4CcgFyhBoGDcKt8EQmQpzzp-Wgk',
    appId: '1:430029536167:web:234678dbb6420a27c6d482',
    messagingSenderId: '430029536167',
    projectId: 'pai-project-ai',
    authDomain: 'pai-project-ai.firebaseapp.com',
    storageBucket: 'pai-project-ai.firebasestorage.app',
    measurementId: 'G-NS2VHZVQVE',
  );
}
